### ISSUE TITLE
Player's progress bar in webreport videos obscures patient's feet

### ISSUE THREAD

**Issue by andreyzhd** [NCH-Motion-Laboratory/gaitutils#12]
Even if the progress bar itself does not obscure the feet, the player window adds a semiopaque area around the progress bar that degrades the video quality in the feet area. The problem doesn't happen for the overlay videos as they have a black frame around the actual video.
One straightforward solution is just to add a black stripe below each non-overlay video.

**Comment by jjnurminen** [comment]
A longstanding issue. The ideal solution might be to ditch the Chrome video player and create/obtain a Dash video player component that would handle also other useful things, like synchronization with gait curves. (I believe that Dash components are just lightly wrapped React components, but never looked deeply into this).

**Comment by jjnurminen** [comment]
Here's a Dash video player component that wraps ReactPlayer: https://github.com/plotly/dash-player
It might be an improvement on Chrome player even out of the box, or at least a starting point. It seems to allow e.g. seeking.

**Comment by jjnurminen** [comment]
I think this was resolved by adding video player options
